title: Choctaw Indian Fair
author: Sonny Mattera
email: sonny.mattera@choctaw.org
description: Greetings from the Choctaw Indian Reservation. We invite you to join us 
  July 14-17 for our 71st annual Choctaw Indian Fair. The fair takes place on our 
  centuries-old homeland in beautiful Choctaw, Mississippi. We gather each July to 
  celebrate our heritage and share our beautiful and vibrant culture with our friends 
  and neighbors.

# social links
facebook_username: choctawindianfair
twitter_username: MsChoctawFair
youtube_channel: Choctawindianfair39350

show_excerpts: true 